---- OPERATIONAL DB TABLES ----

USE DCMDB;

CREATE TABLE USER (
USER_ID INT,
USER_NAME VARCHAR(255), 
USER_PWD VARCHAR(255),
USER_EMAIL VARCHAR(255),
USER_MOBILE VARCHAR(50),
USER_POSTCODE SMALLINT,
USER_SEARCH_RDS VARCHAR(255),
USER_REG_DTTM DATETIME,
PRIMARY KEY (USER_ID)
);


CREATE TABLE `USER_ENCRYPT` (
  `USER_ID` int NOT NULL,
  `USER_NAME` varchar(255) DEFAULT NULL,
  `USER_PWD_HASH` varchar(128) DEFAULT NULL,
  `USER_PWD_SALT` varchar(64) DEFAULT NULL,
  `USER_EMAIL` varchar(255) DEFAULT NULL,
  `USER_MOBILE` varchar(50) DEFAULT NULL,
  `USER_POSTCODE` smallint DEFAULT NULL,
  `USER_SEARCH_RDS` varchar(255) DEFAULT NULL,
  `USER_REG_DTTM` datetime DEFAULT NULL,
  PRIMARY KEY (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE USER_ORDER (
ORDER_ID VARCHAR(30),
USER_ID INT,
STORE_ID INT,
ORDER_TOTAL_PRICE DECIMAL(10,2),
ORDER_TOTAL_DISCOUNT DECIMAL(10,2),
ORDER_DTTM DATETIME,
PRIMARY KEY (ORDER_ID)
);


CREATE TABLE ORDER_ITEM (
ORDER_ID VARCHAR(30),
ITEM_ID INT,
ORDER_ITEM_QTY SMALLINT,
ORDER_ITEM_BASE_PRICE DECIMAL(8,2),
ORDER_ITEM_DISCOUNT_PRICE DECIMAL(8,2),
PRIMARY KEY (ORDER_ID, ITEM_ID, ORDER_ITEM_BASE_PRICE)
);


CREATE TABLE ITEM_PRICE_HIST (
ITEM_ID INT,
COM_ID INT,
IPH_DATE DATE,
IPH_ITEM_BASE_PRICE DECIMAL(8,2),
IPH_ITEM_DISCOUNT_PRICE DECIMAL(8,2),
IPH_ITEM_DISCOUNT_PCT DECIMAL(4,2),
PRIMARY KEY (ITEM_ID, COM_ID, IPH_DATE)
);


CREATE TABLE ITEM_PRICE_CURRENT (
ITEM_ID INT,
COM_ID INT,
IP_ITEM_BASE_PRICE DECIMAL(8,2),
IP_ITEM_DISCOUNT_PRICE DECIMAL(8,2),
IP_ITEM_DISCOUNT_PCT DECIMAL(4,2),
IP_FOUR_WK_HIGHEST_PRICE DECIMAL(8,2),
IP_FOUR_WK_LOWEST_PRICE DECIMAL(8,2),
PRIMARY KEY (ITEM_ID, COM_ID)
);


CREATE TABLE ITEM_PRICE_PREDICTION (
ITEM_ID INT,
COM_ID INT,
IPP_NEXT_WK_DISCOUNT_PBTY DECIMAL(5,4),
IPP_NEXT_WK_DISCOUNT_PRICE DECIMAL(8,2),
PRIMARY KEY (ITEM_ID)
);


CREATE TABLE STORE (
STORE_ID INT,
COM_ID INT,
STORE_POSTCODE SMALLINT,
STORE_ADDRESS VARCHAR(255),
STORE_GPS VARCHAR(255),
STORE_NAME VARCHAR(255),
PRIMARY KEY (STORE_ID)
);


CREATE TABLE COMPANY (
COM_ID INT,
COM_NAME VARCHAR(255),
PRIMARY KEY (COM_ID)
);


CREATE TABLE USER_ITEM_CART (
USER_ID INT,
ITEM_ID INT,
PRIMARY KEY (USER_ID, ITEM_ID)
);


CREATE TABLE CATEGORY (
CAT_ID INT,
CAT_NAME VARCHAR(255),
PRIMARY KEY (CAT_ID)
);


CREATE TABLE RECOMMEND_ITEM (
USER_ID INT,
ITEM_ID INT,
COM_ID INT,
PRIMARY KEY (USER_ID,ITEM_ID,COM_ID)
);


CREATE TABLE ITEM_IMAGE (
  ITEM_IMAGE_ID INT ,
  IMAGE TEXT,
  PRIMARY KEY (ITEM_IMAGE_ID)
);




-- 2023T1 DISCOUNTMATE DB SCHEMA ENHANCEMENT

CREATE TABLE `STAGING_COLES_ITEM_PRICE` (
  `COLES_PRICE_DATE` DATE DEFAULT NULL,
  `COLES_ITEM_ID` VARCHAR(255) DEFAULT NULL,
  `COLES_ITEM_NAME` VARCHAR(255) DEFAULT NULL,
  `COLES_ITEM_PRICE` VARCHAR(255) DEFAULT NULL,
  `COLES_ITEM_UNIT_PRICE` VARCHAR(255) DEFAULT NULL,
  `COLES_ITEM_PROMO` VARCHAR(255) DEFAULT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_0900_AI_CI;


CREATE TABLE `STAGING_WOOLY_ITEM_PRICE` (
  `WOOLY_PRICE_DATE` DATE DEFAULT NULL,
  `WOOLY_ITEM_ID` VARCHAR(255) DEFAULT NULL,
  `WOOLY_ITEM_NAME` VARCHAR(255) DEFAULT NULL,
  `WOOLY_ITEM_PRICE` VARCHAR(255) DEFAULT NULL,
  `WOOLY_ITEM_UNIT_PRICE` VARCHAR(255) DEFAULT NULL,
  `WOOLY_ITEM_PROMO_1` VARCHAR(255) DEFAULT NULL,
  `WOOLY_ITEM_PROMO_2` VARCHAR(255) DEFAULT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_0900_AI_CI;


CREATE TABLE `ODS_COLES_ITEM_PRICE` (
  `COLES_PRICE_DATE` DATE DEFAULT NULL,
  `ITEM_ID` INT DEFAULT NULL,
  `COLES_ITEM_NAME` VARCHAR(255) DEFAULT NULL,
  `COLES_ITEM_PRICE` DECIMAL(8,2) DEFAULT NULL,
  `COLES_ITEM_UNIT_PRICE` VARCHAR(255) DEFAULT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_0900_AI_CI;


CREATE TABLE `ODS_WOOLY_ITEM_PRICE` (
  `WOOLY_PRICE_DATE` DATE DEFAULT NULL,
  `ITEM_ID` INT DEFAULT NULL,
  `WOOLY_ITEM_NAME` VARCHAR(255) DEFAULT NULL,
  `WOOLY_ITEM_PRICE` DECIMAL(8,2) DEFAULT NULL,
  `WOOLY_ITEM_UNIT_PRICE` VARCHAR(255) DEFAULT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_0900_AI_CI;


CREATE TABLE `ITEM_PRICE_MIN_MAX` (
  `ITEM_ID` INT NOT NULL,
  `MAX_ITEM_PRICE` DECIMAL(8,2) DEFAULT NULL,
  `MIN_ITEM_PRICE` DECIMAL(8,2) DEFAULT NULL,
  PRIMARY KEY (`ITEM_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_0900_AI_CI;


-- CREATE STAGING_ORDER_TRANSACTION
CREATE TABLE STAGING_ORDER_TRANSACTION (
USER_ID VARCHAR(255) DEFAULT NULL,
USER_ORDER_DATE VARCHAR(255) DEFAULT NULL,
ITEM_DESC VARCHAR(255) DEFAULT NULL
);


-- CREATE LOOKUP_ORDER_TRANSACTION_ITEM_ID
CREATE TABLE LOOKUP_ORDER_TRANSACTION_ITEM_ID (
ITEM_DESC VARCHAR(255) DEFAULT NULL,
LOOKUP_ITEM_NAME VARCHAR(255) DEFAULT NULL,
LOOKUP_ITEM_ID VARCHAR(255) DEFAULT NULL
);


-- Upgraded ITEM with ITEM_MEASUREMENT, ITEM_UNIT, ITEM_UNIT_PRICE added
CREATE TABLE `ITEM` (
  `ITEM_ID` int NOT NULL,
  `CAT_ID` int DEFAULT NULL,
  `ITEM_NAME` varchar(255) DEFAULT NULL,
  `ITEM_PRICE` decimal(6,2) DEFAULT NULL,
  `ITEM_MEASUREMENT` TINYINT DEFAULT NULL,
  `ITEM_UNIT` varchar(10),
  `ITEM_UNIT_PRICE` decimal(6,2) DEFAULT NULL,
  `ITEM_IMAGE_ID` text,
  ITEM_DESC varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ITEM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- Table for Item Recommender Collaborative Filtering Model use
CREATE TABLE ITEM_RATING (
USER_ID INT,
ITEM_ID INT,
RATING INT
);


-- Table for Item Recommender Result
CREATE TABLE `RECOMMEND_ITEM_COLLAB_FILTER` (
  `RCM_USER_ID` int NOT NULL,
  `RCM_ITEM_ID` int NOT NULL,
  `RCM_COM_ID` int NOT NULL,
  RCM_INSERT_DATE DATE
#  PRIMARY KEY (`RCM_USER_ID`,`RCM_ITEM_ID`,`RCM_COM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


create table STAGING_OCR_USER_ORDER (
RECEIPT_ID varchar(255) not null,
ORDER_DATE date not null,
SUPERMARKET_NAME varchar(255) not null,
STORE_NAME varchar(255) not null,
ITEM_NAME varchar(255) not null,
ITEM_PRICE varchar(50) not null,
PROCESSED varchar(50) not null,
RECEIPT_USER_ID varchar(50) not null,
RECEIPT_STORE_ID varchar(50) not null
);


Create table STAGING_API_ITEM_PRICE (
COMPANY_NAME varchar(255),
ITEM_NAME varchar(255),
ITEM_PRICE varchar(10),
REC_INSERT_DATE date
);


CREATE TABLE `ODS_WOOLY_ITEM_PRICE_2_YEARS` (
  `WOOLY_PRICE_DATE` date DEFAULT NULL,
  `WOOLY_ITEM_CODE` int DEFAULT NULL,
  `WOOLY_ITEM_NAME` varchar(255) DEFAULT NULL,
  `WOOLY_ITEM_PRICE` decimal(8,2) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `ITEM_SIM` (
  `ITEM1_ID` int NOT NULL,
  `ITEM2_ID` int NOT NULL,
  `SIM` int DEFAULT NULL,
  PRIMARY KEY (`ITEM1_ID`,`ITEM2_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `LOOKUP_ORDER_TRANSACTION_ITEM_ID` (
  `ITEM_DESC` varchar(255) DEFAULT NULL,
  `LOOKUP_ITEM_NAME` varchar(255) DEFAULT NULL,
  `LOOKUP_ITEM_ID` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

